GET http://localhost:8000/v1/products HTTP/1.1

###
POST http://localhost:8000/v1/products/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=t-shirts
&quantity=25



###
DELETE http://localhost:8000/v1/products/614fe49a542d64f2de7be1bf HTTP/1.1

###
POST  http://localhost:8000/v1/products/615a62eb61df2d14c3a802df/update_quantity/?number=100 HTTP/1.1


###              ******** DEPLYMENT TEST ***********
GET https://ecommerceapi2.herokuapp.com/v1/products HTTP/1.1

###
POST https://ecommerceapi2.herokuapp.com/v1/products/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=headphones
&quantity=35

###
DELETE https://ecommerceapi2.herokuapp.com/v1/products/614fe49a542d64f2de7be1bf HTTP/1.1

###
POST  https://ecommerceapi2.herokuapp.com/v1/products/614fe49a542d64f2de7be1bf/update_quantity/?number=100 HTTP/1.1

